import type { GetStaticProps } from "next";
import { BlogPost, getBlogPosts } from "@/utils/api-service";
import BlogList from "@/components/BlogList";
import Head from "next/head";

interface HomeProps {
  initialPosts: BlogPost[];
  error?: string;
}

export default function Home({ initialPosts, error }: HomeProps) {
  console.log("error", error);

  return (
    <>
      <Head>
        <title>My Blogs</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>
        {initialPosts.length === 0 || error ? (
          <div className="container py-8">
            <h1 className="text-xl font-bold mb-8 text-center text-gray-800">
              {error || "No blog posts found"}
            </h1>
          </div>
        ) : (
          <BlogList post={initialPosts} />
        )}
      </div>
    </>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  try {
    const posts = await getBlogPosts();

    return {
      props: {
        initialPosts: posts || [],
      },
      revalidate: 60,
    };
  } catch (error) {
    return {
      props: {
        initialPosts: [],
        error: error || "Failed to fetch blog posts.",
      },
      revalidate: 60,
    };
  }
};
