import type { GetStaticProps } from "next";
import { BlogPost, getBlogPosts } from "@/utils/api-service";
import BlogList from "@/components/BlogList";
import Head from "next/head";

interface HomeProps {
  initialPosts: BlogPost[];
}

export default function Home({ initialPosts }: HomeProps) {
  return (
    <>
      <Head>
        <title>My Blogs</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="container">
        <BlogList post={initialPosts} />
      </div>
    </>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const posts = await getBlogPosts();
  return {
    props: {
      initialPosts: posts,
    },
    revalidate: 60,
  };
};
